### ISSUE TITLE
could not find package app_lock_flutter at https://pub.dev

### ISSUE THREAD

**Issue by a-3isa** [Ninad7n/AppLockFlutter#7]
Hi, i am trying to use your project but face this problem.
`Launching lib\main.dart on sdk gphone64 x86 64 in debug mode...
Invalid depfile: D:\Work\tthkr\.dart_tool\flutter_build\1024968b7629da67b21c8fbfbb610857\kernel_snapshot.d
Invalid depfile: D:\Work\tthkr\.dart_tool\flutter_build\1024968b7629da67b21c8fbfbb610857\kernel_snapshot.d
Error: Couldn't resolve the package 'app_lock_flutter' in 'package:app_lock_flutter/services/init.dart'.
Error: Couldn't resolve the package 'app_lock_flutter' in 'package:app_lock_flutter/services/themes.dart'.
Error: Couldn't resolve the package 'app_lock_flutter' in 'package:app_lock_flutter/screens/home.dart'.
lib/main.dart:3:8: Error: Not found: 'package:app_lock_flutter/services/init.dart'
import 'package:app_lock_flutter/services/init.dart';
       ^
lib/main.dart:4:8: Error: Not found: 'package:app_lock_flutter/services/themes.dart'
import 'package:app_lock_flutter/services/themes.dart';
       ^
lib/screens/splash.dart:3:8: Error: Not found: 'package:app_lock_flutter/screens/home.dart'
import 'package:app_lock_flutter/screens/home.dart';
       ^
lib/main.dart:10:9: Error: Method not found: 'initialize'.
  await initialize();
        ^^^^^^^^^^
lib/main.dart:21:14: Error: The getter 'CustomTheme' isn't defined for the class 'MyApp'.
 - 'MyApp' is from 'package:tthkr/main.dart' ('lib/main.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'CustomTheme'.
      theme: CustomTheme.dark,
             ^^^^^^^^^^^
lib/screens/splash.dart:20:39: Error: Couldn't find constructor 'HomePage'.
          builder: (context) => const HomePage(),
                                      ^^^^^^^^
Unhandled exception:
FileSystemException(uri=org-dartlang-untranslatable-uri:package%3Aapp_lock_flutter%2Fservices%2Finit.dart; message=StandardFileSystem only supports file:* and data:* URIs)
#0      StandardFileSystem.entityForUri (package:front_end/src/api_prototype/standard_file_system.dart:34)
#1      asFileUri (package:vm/kernel_front_end.dart:748)
#2      writeDepfile (package:vm/kernel_front_end.dart:886)
<asynchronous suspension>
#3      FrontendCompiler.compile (package:frontend_server/frontend_server.dart:673)
<asynchronous suspension>
#4      starter (package:frontend_server/starter.dart:101)
<asynchronous suspension>
#5      main (file:///C:/b/s/w/ir/x/w/sdk/pkg/frontend_server/bin/frontend_server_starter.dart:13)
<asynchronous suspension>
Target kernel_snapshot failed: Exception

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileFlutterBuildDebug'.
> Process 'command 'D:\flutter_windows_3.13.9-stable\flutter\bin\flutter.bat'' finished with non-zero exit value 1

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 27s
Error: Gradle task assembleDebug failed with exit code 1

Exited (1).
`

**Comment by a-3isa** [comment]
solved by adding app_lock_flutter to pupspec.yaml dependencies
